### ISSUE TITLE
Creating Android Hyperskill Problems

### ISSUE THREAD

**Issue by RedJocker** [hyperskill/hs-test#134]
We have a new content creator that is responsible for creating content for composables and he is trying to create coding assignments using this document as reference, but he is not being able to do it

https://github.com/hyperskill/hs-test/wiki/Creating-Hyperskill-problems

we have never done something like this before and I'm not sure this is possible. 
We even opened a feature request on this [card]( https://trello.com/c/h4LKcvJ1/386-adding-libraries-to-coding-challenge-runtime-classpath) some time ago because we have been working with the premise that it is not possible to make coding assignments including android libraries, which is really bad for us.  

Can you give us android specifics clarification on this matter?
Is it possible to have coding assignments with android libraries using the steps provided on this document above?

**Comment by aaaaaa2493** [comment]
@RedJocker Hi!
Since `hs-test` cannot test Android solutions in general then it's impossible to create Android problems using `hs-test`.

However, text in the instruction is correct for Android problems as well, so they have to follow the same restrictions (no internet and no additional libraries) if you want the solutions to be testable in the web interface and you can use internet and libraries if you want the solution to be testable in IDE only.

At the moment we have no support for testing Android in the web interface (we have no environment being set up i.e. no Docker image). But you definitely can create Android problem that can be solvable in the IDE only. It should be possible right now without any additional support from Hyperskill.

**Comment by RedJocker** [comment]
For now creating Android problem that can be solvable in the IDE only would be a step forward, but [@razoTRON](https://github.com/RazoTRON) is having problems trying to create one.

I have asked him to come here give the specifics, but there seems to be some errors doing the upload of the content to stepik and them settings.gradle and project level build.gradle end up not having the right version when trying to download it back from stepik

**Comment by RazoTRON** [comment]
> @RedJocker Hi!
> Since `hs-test` cannot test Android solutions in general then it's impossible to create Android problems using `hs-test`.
> 
> However, text in the instruction is correct for Android problems as well, so they have to follow the same restrictions (no internet and no additional libraries) if you want the solutions to be testable in the web interface and you can use internet and libraries if you want the solution to be testable in IDE only.
> 
> At the moment we have no support for testing Android in the web interface (we have no environment being set up i.e. no Docker image). But you definitely can create Android problem that can be solvable in the IDE only. It should be possible right now without any additional support from Hyperskill.

Приветствую, Владимир! Столкнулся я с такой проблемой: копирую существующий проект по инструкции, вношу необходимые изменения, все работает отлично, тесты проходит. Загружаю обратно на степик как новый урок. После этого, если уже скопировать уже этот новый проект, загружается весь код, но build.gradle и gradle.settings имеют уже совершенно другое содержание! То есть совершенно не те, которые я загружал ранее. Соответственно, задание уже невозможно выполнить не изменив эти файлы. Стоит отметить, что при загрузке в студии выскакивает ошибка, что урок не загрузился, но он все равно появляется на степике. Проблема и в Android Studio, и в Intellij IDEA. 

(Hello Vladimir!  I ran into this problem: I copy an existing project according to the instructions, make the necessary changes, everything works fine, the tests pass.  Uploading back to stepik as a new lesson.  After that, if you already copy this new project, all the code is loaded, but build.gradle and gradle.settings have completely different content!  That is, absolutely not the ones that I uploaded earlier.  Accordingly, the task can no longer be completed without changing these files.  It is worth noting that when loading in the studio, an error pops up that the lesson has not loaded, but it still appears on the step.  The problem is in both Android Studio and Intellij IDEA.)

**Comment by aaaaaa2493** [comment]
@inuur Please check this

**Comment by inuur** [comment]
The issue doesn't relate to hs-test, and we will discuss in trello.
